name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore Jantimiser/Jantimiser.sln
    - name: Build
      run: dotnet build Jantimiser/Jantimiser.sln --no-restore
    - name: Test
      run: dotnet test Jantimiser/Jantimiser.sln --no-build --verbosity normal
