name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet Jantimiser/Jantimiser.sln restore
    - name: Build
      run: dotnet Jantimiser/Jantimiser.sln build --no-restore
    - name: Test
      run: dotnet Jantimiser/Jantimiser.sln test --no-build --verbosity normal
